# -*- coding: utf-8 -*-
"""Calculadora con interfaz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JndPOZS0ygl-OppC53QZNBzpV9cjmMom
"""

def solicitar_numero(mensaje):
    """Solicita un número al usuario y verifica que sea válido."""
    while True:
        try:
            return float(input(mensaje))  # Convierte la entrada en número decimal
        except ValueError:
            print("❌ Error: Ingresa un número válido.")


def solicitar_operacion():
    """Solicita una operación matemática válida."""
    operaciones_validas = {"+", "-", "*", "/"}
    while True:
        operacion = input("➕➖✖️➗ Ingresa la operación matemática (+, -, *, /) o '=' para calcular: ").strip()
        if operacion in operaciones_validas or operacion == "=":
            return operacion
        else:
            print("❌ Error: Operación inválida. Ingresa +, -, * o /")


def calcular(num1, operacion, num2):
    """Realiza la operación matemática y devuelve el resultado."""
    try:
        if operacion == "+":
            return num1 + num2
        elif operacion == "-":
            return num1 - num2
        elif operacion == "*":
            return num1 * num2
        elif operacion == "/":
            if num2 == 0:
                return "❌ Error: No se puede dividir por cero."
            return num1 / num2
    except Exception as e:
        return f"❌ Error: {e}"


while True:  # 🟢 Inicia el programa principal
    print("\n🧮 Bienvenido a la calculadora\n")


    while True:  # 📌 Paso 1: Pedir el primer número
        num1 = solicitar_numero("🔢 Ingresa el primer número: ")

    # 🔄 Paso 2 y 3: Elegir operación y segundo número hasta que se elija "="
        operacion = solicitar_operacion()
        if operacion == "=":
            print("⚠️ Debes ingresar al menos una operación antes de calcular.")
            continue  # Pide una operación válida antes de calcular

        num2 = solicitar_numero("🔢 Ingresa el segundo número: ")
        resultado = calcular(num1, operacion, num2)
        print(f"✅ Resultado: {num1} {operacion} {num2} = {resultado}")

        # Actualiza num1 para la próxima operación en cadena
        num1 = resultado

        # Preguntar si desea continuar o calcular
        continuar = input("🟢 ¿Quieres seguir operando? (y/n): ").strip().lower()
        if continuar != "y":
            print("👋 ¡Gracias por usar la calculadora!")
            exit()